// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.14.0
// source: protos/diffs.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Export io
type ContentType int32

const (
	ContentType_JSON     ContentType = 0
	ContentType_HTML     ContentType = 1
	ContentType_WIKITEXT ContentType = 2
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "JSON",
		1: "HTML",
		2: "WIKITEXT",
	}
	ContentType_value = map[string]int32{
		"JSON":     0,
		"HTML":     1,
		"WIKITEXT": 2,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_diffs_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_protos_diffs_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_protos_diffs_proto_rawDescGZIP(), []int{0}
}

type ExportRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DbName string `protobuf:"bytes,1,opt,name=db_name,json=dbName,proto3" json:"db_name,omitempty"`
	// Deprecated: Do not use.
	ContentType ContentType `protobuf:"varint,2,opt,name=content_type,json=contentType,proto3,enum=diffs.ContentType" json:"content_type,omitempty"`
	Workers     int32       `protobuf:"varint,3,opt,name=workers,proto3" json:"workers,omitempty"`
	Ns          int32       `protobuf:"varint,4,opt,name=ns,proto3" json:"ns,omitempty"`
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_diffs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_diffs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_protos_diffs_proto_rawDescGZIP(), []int{0}
}

func (x *ExportRequest) GetDbName() string {
	if x != nil {
		return x.DbName
	}
	return ""
}

// Deprecated: Do not use.
func (x *ExportRequest) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_JSON
}

func (x *ExportRequest) GetWorkers() int32 {
	if x != nil {
		return x.Workers
	}
	return 0
}

func (x *ExportRequest) GetNs() int32 {
	if x != nil {
		return x.Ns
	}
	return 0
}

type ExportResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Errors int32 `protobuf:"varint,2,opt,name=errors,proto3" json:"errors,omitempty"`
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_diffs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_diffs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_protos_diffs_proto_rawDescGZIP(), []int{1}
}

func (x *ExportResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ExportResponse) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

// Tidy io
type TidyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TidyRequest) Reset() {
	*x = TidyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_diffs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TidyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TidyRequest) ProtoMessage() {}

func (x *TidyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_diffs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TidyRequest.ProtoReflect.Descriptor instead.
func (*TidyRequest) Descriptor() ([]byte, []int) {
	return file_protos_diffs_proto_rawDescGZIP(), []int{2}
}

type TidyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Errors int32 `protobuf:"varint,2,opt,name=errors,proto3" json:"errors,omitempty"`
}

func (x *TidyResponse) Reset() {
	*x = TidyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_diffs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TidyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TidyResponse) ProtoMessage() {}

func (x *TidyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_diffs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TidyResponse.ProtoReflect.Descriptor instead.
func (*TidyResponse) Descriptor() ([]byte, []int) {
	return file_protos_diffs_proto_rawDescGZIP(), []int{3}
}

func (x *TidyResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TidyResponse) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

// TidyRemote io
type TidyRemoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *TidyRemoteRequest) Reset() {
	*x = TidyRemoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_diffs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TidyRemoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TidyRemoteRequest) ProtoMessage() {}

func (x *TidyRemoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_diffs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TidyRemoteRequest.ProtoReflect.Descriptor instead.
func (*TidyRemoteRequest) Descriptor() ([]byte, []int) {
	return file_protos_diffs_proto_rawDescGZIP(), []int{4}
}

type TidyRemoteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Errors int32 `protobuf:"varint,2,opt,name=errors,proto3" json:"errors,omitempty"`
}

func (x *TidyRemoteResponse) Reset() {
	*x = TidyRemoteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_diffs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TidyRemoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TidyRemoteResponse) ProtoMessage() {}

func (x *TidyRemoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_diffs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TidyRemoteResponse.ProtoReflect.Descriptor instead.
func (*TidyRemoteResponse) Descriptor() ([]byte, []int) {
	return file_protos_diffs_proto_rawDescGZIP(), []int{5}
}

func (x *TidyRemoteResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *TidyRemoteResponse) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

// Aggregate io description
type AggregateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AggregateRequest) Reset() {
	*x = AggregateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_diffs_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateRequest) ProtoMessage() {}

func (x *AggregateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_diffs_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateRequest.ProtoReflect.Descriptor instead.
func (*AggregateRequest) Descriptor() ([]byte, []int) {
	return file_protos_diffs_proto_rawDescGZIP(), []int{6}
}

type AggregateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Total  int32 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Errors int32 `protobuf:"varint,2,opt,name=errors,proto3" json:"errors,omitempty"`
}

func (x *AggregateResponse) Reset() {
	*x = AggregateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_diffs_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AggregateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregateResponse) ProtoMessage() {}

func (x *AggregateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_diffs_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregateResponse.ProtoReflect.Descriptor instead.
func (*AggregateResponse) Descriptor() ([]byte, []int) {
	return file_protos_diffs_proto_rawDescGZIP(), []int{7}
}

func (x *AggregateResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *AggregateResponse) GetErrors() int32 {
	if x != nil {
		return x.Errors
	}
	return 0
}

var File_protos_diffs_proto protoreflect.FileDescriptor

var file_protos_diffs_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x64, 0x69, 0x66, 0x66, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x64, 0x69, 0x66, 0x66, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x0d,
	0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x64, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x64, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x64,
	0x69, 0x66, 0x66, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x42, 0x02, 0x18, 0x01, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x6e, 0x73, 0x22, 0x3e, 0x0a, 0x0e, 0x45,
	0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x0d, 0x0a, 0x0b, 0x54,
	0x69, 0x64, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3c, 0x0a, 0x0c, 0x54, 0x69,
	0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x54, 0x69, 0x64, 0x79,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a,
	0x12, 0x54, 0x69, 0x64, 0x79, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x73, 0x22, 0x12, 0x0a, 0x10, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x11, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2a, 0x2f, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x53, 0x4f, 0x4e, 0x10,
	0x00, 0x12, 0x08, 0x0a, 0x04, 0x48, 0x54, 0x4d, 0x4c, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x57,
	0x49, 0x4b, 0x49, 0x54, 0x45, 0x58, 0x54, 0x10, 0x02, 0x32, 0xf2, 0x01, 0x0a, 0x05, 0x44, 0x69,
	0x66, 0x66, 0x73, 0x12, 0x35, 0x0a, 0x06, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x14, 0x2e,
	0x64, 0x69, 0x66, 0x66, 0x73, 0x2e, 0x45, 0x78, 0x70, 0x6f, 0x72, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x64, 0x69, 0x66, 0x66, 0x73, 0x2e, 0x45, 0x78, 0x70, 0x6f,
	0x72, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x04, 0x54, 0x69,
	0x64, 0x79, 0x12, 0x12, 0x2e, 0x64, 0x69, 0x66, 0x66, 0x73, 0x2e, 0x54, 0x69, 0x64, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x64, 0x69, 0x66, 0x66, 0x73, 0x2e, 0x54,
	0x69, 0x64, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x54,
	0x69, 0x64, 0x79, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x12, 0x18, 0x2e, 0x64, 0x69, 0x66, 0x66,
	0x73, 0x2e, 0x54, 0x69, 0x64, 0x79, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x69, 0x66, 0x66, 0x73, 0x2e, 0x54, 0x69, 0x64, 0x79,
	0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e,
	0x0a, 0x09, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x64, 0x69,
	0x66, 0x66, 0x73, 0x2e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x64, 0x69, 0x66, 0x66, 0x73, 0x2e, 0x41, 0x67, 0x67,
	0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x14,
	0x5a, 0x12, 0x6f, 0x6b, 0x61, 0x70, 0x69, 0x2d, 0x64, 0x69, 0x66, 0x66, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_diffs_proto_rawDescOnce sync.Once
	file_protos_diffs_proto_rawDescData = file_protos_diffs_proto_rawDesc
)

func file_protos_diffs_proto_rawDescGZIP() []byte {
	file_protos_diffs_proto_rawDescOnce.Do(func() {
		file_protos_diffs_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_diffs_proto_rawDescData)
	})
	return file_protos_diffs_proto_rawDescData
}

var file_protos_diffs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_diffs_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protos_diffs_proto_goTypes = []interface{}{
	(ContentType)(0),           // 0: diffs.ContentType
	(*ExportRequest)(nil),      // 1: diffs.ExportRequest
	(*ExportResponse)(nil),     // 2: diffs.ExportResponse
	(*TidyRequest)(nil),        // 3: diffs.TidyRequest
	(*TidyResponse)(nil),       // 4: diffs.TidyResponse
	(*TidyRemoteRequest)(nil),  // 5: diffs.TidyRemoteRequest
	(*TidyRemoteResponse)(nil), // 6: diffs.TidyRemoteResponse
	(*AggregateRequest)(nil),   // 7: diffs.AggregateRequest
	(*AggregateResponse)(nil),  // 8: diffs.AggregateResponse
}
var file_protos_diffs_proto_depIdxs = []int32{
	0, // 0: diffs.ExportRequest.content_type:type_name -> diffs.ContentType
	1, // 1: diffs.Diffs.Export:input_type -> diffs.ExportRequest
	3, // 2: diffs.Diffs.Tidy:input_type -> diffs.TidyRequest
	5, // 3: diffs.Diffs.TidyRemote:input_type -> diffs.TidyRemoteRequest
	7, // 4: diffs.Diffs.Aggregate:input_type -> diffs.AggregateRequest
	2, // 5: diffs.Diffs.Export:output_type -> diffs.ExportResponse
	4, // 6: diffs.Diffs.Tidy:output_type -> diffs.TidyResponse
	6, // 7: diffs.Diffs.TidyRemote:output_type -> diffs.TidyRemoteResponse
	8, // 8: diffs.Diffs.Aggregate:output_type -> diffs.AggregateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_diffs_proto_init() }
func file_protos_diffs_proto_init() {
	if File_protos_diffs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_diffs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_diffs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExportResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_diffs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TidyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_diffs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TidyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_diffs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TidyRemoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_diffs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TidyRemoteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_diffs_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_diffs_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AggregateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_diffs_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_diffs_proto_goTypes,
		DependencyIndexes: file_protos_diffs_proto_depIdxs,
		EnumInfos:         file_protos_diffs_proto_enumTypes,
		MessageInfos:      file_protos_diffs_proto_msgTypes,
	}.Build()
	File_protos_diffs_proto = out.File
	file_protos_diffs_proto_rawDesc = nil
	file_protos_diffs_proto_goTypes = nil
	file_protos_diffs_proto_depIdxs = nil
}
